version: "3.8"
services:
  apache-web:
    build:
      context: ./ 
      dockerfile: Dockerfile    
    restart: 'no'
    volumes:
      - ./projects/app/:/home/projects/app/
    ports:
      - 8000:80
 